#theme: jekyll-theme-hacker
#title: welcome to Amrita's homepage!
#description: It's still a work-in-progress

# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- vendor

# 2. Installed plugin gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- github-pages

# 3. Gem settings
sass:
  style: compressed
  sass_dir: _sass

paginate: 8 # jekyll-paginate > items per page
paginate_path: "/blog/page:num/" # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # base url for jekyll mentions

compress_html:
  clippings: all

twitter:
  username: amritasuresh # jekyll-seo-tag > Owners twitter username

author: Amrita Suresh # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Amrita Suresh # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/anotheramrita
    - https://www.facebook.com/amritasuresh
    - https://www.linkedin.com/in/amritasuresh
    - https://github.com/amritasuresh

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: /:categories/:title/  # define url construction
timezone: Europe/Paris # Timezone for blog posts and alike

# 6. Site wide defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/img/kunal-logo.png" # Default image for sharing

  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: tag
    values:
      layout: tag
collections:
  tag:
      output: true

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Amrita Suresh" # Site name or title, also used in jekyll-seo-tag
#logo: "/assets/img/kunal-logo.png" # Site logo, also used in jekyll-seo-tag

# Site description and default description, also used in jekyll-seo-tag
url: "https://amritasuresh.github.io" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/amritasuresh/amritasuresh.github.io"
disqus: "amritasuresh-github-io"
#avatarurl: "https://avatars0.githubusercontent.com/u/4623624"

# site verification
webmaster_verifications:
  google: sCRGg28ReGiDdQ4JQ75b6RCTtmBD9J6QQwh1kpIMDAU

# default markdown processor and highlighter
markdown: kramdown
highlighter: rouge
error_mode: strict

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

#site credits
navigation_footer:
  Adopted Alembic Theme: https://alembic.darn.es/

contact:
  email:      amritasuresh2209@gmail.com
  github:     https://github.com/amritasuresh
  linkedin:   https://www.linkedin.com/in/amritasuresh
  twitter:    https://twitter.com/anotheramrita


